### ISSUE TITLE
Client Project Setup

### ISSUE THREAD

**Issue by MichealPearce** [MichealPearce/potential-memory#2]
Need to setup the client vite project to have a few choice plugins.

https://github.com/antfu/unplugin-vue-components
https://github.com/JohnCampionJr/vite-plugin-vue-layouts
https://github.com/hannoeru/vite-plugin-pages

**Comment by MichealPearce** [comment]
Another good thing to add to the client project setup would be vue snippets for quickly creating components. My old ones can be found here:
https://github.com/UnitedLands/website/blob/master/.vscode/vue.code-snippets#L6-L48

These should be added to `client/.vscode/vue.code-snippets`

Another thing to add would be SASS

**Comment by LifeOfKnull** [comment]
branching off `main` to `issue-2` to work

**Comment by MichealPearce** [comment]
completed with #4
