### ISSUE TITLE
root scripts for dev/build/start

### ISSUE THREAD

**Issue by MichealPearce** [MichealPearce/potential-memory#6]
we need scripts in the root `package.json` to be able to run the different projects (shared, server, client) in our app. When in development, we want to run both the server and client at the same time, and during build we want to run each after the other.

To do this we will use a package called `npm-run-all` (can be used with yarn too).
https://www.npmjs.com/package/npm-run-all

Scripts have already been added in the root `package.json` to quickly access the server and client workspaces (via `yarn client dev` for example). So now we just need scripts for running both the server and client scripts at the same time.

An example for the dev process scripts would be:
```
"dev:server": "yarn server dev",
"dev:client:" "yarn client dev",
"dev": "run-p dev:server dev:client",
```

**Comment by MichealPearce** [comment]
`npm-run-all` should be added to the root `package.json` as a dev dependency

**Comment by LifeOfKnull** [comment]
Branching off `main` to `Issue #6` to work
